[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *.internal
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[spoolman]
server: http://192.168.68.156:7912

[update_manager Demon_Klipper_Essentials_Unified]
type: git_repo
path: ~/printer_data/config/Demon_Klipper_Essentials_Unified
origin: https://github.com/3DPrintDemon/Demon_Klipper_Essentials_Unified.git
primary_branch: main
is_system_service: False
managed_services: klipper


[hue]
#   The type of device.  Can be either gpio, klipper_device, rf,
#   tplink_smartplug, tasmota, shelly, homeseer, homeassistant, loxonev1,
#   smartthings, mqtt or hue.
#   This parameter must be provided.
type: hue 

#   A valid ip address or hostname of the Philips Hue Bridge. This
#   parameter must be provided.
address: 192.168.68.109

#   A port number if an alternative Zigbee bridge is used on a HTTP port
#   different from the default 80/443
port: 443

#   The api key used for request authorization.  This option accepts
#   Jinja2 Templates, see the [secrets] section for details.
user: {secrets.hue.api}

#   The device id of the light/socket you want to control.
#   An explanation on how you could get the device id, can be found here:
#   https://developers.meethue.com/develop/get-started-2/#turning-a-light-on-and-off
device_id: 00:17:88:01:09:8c:58:75-0b

#   Set to light to control a single hue light, or group to control a hue light group.
#   If device_type is set to light, the device_id should be the light id,
#   and if the device_type is group, the device_id should be the group id.
#   The default is "light".
device_type: light


# Smart Plug Tapo P110. Needs additional python pack installed.
# If needed Follow steps in this repository https://github.com/mainde/klipper-moonraker-tapo/blob/main/README.md
[power ENDER-7]
type: http
on_url: http://localhost:56427/on
off_url: http://localhost:56427/off
status_url: http://localhost:56427/
response_template:
  {% set resp = http_request.last_response().json() %}
  {% if resp["device_on"] %}
    {"on"}
  {% else %}
    {"off"}
  {% endif %}
bound_services: klipper
off_when_shutdown: False
locked_while_printing: True
restart_klipper_when_powered: True
on_when_job_queued: True

[update_manager Spoolman]
type: zip
channel: stable
repo: Donkie/Spoolman
path: /home/pi/Spoolman
virtualenv: .venv
requirements: requirements.txt
persistent_files:
  .venv
  .env
managed_services: Spoolman


[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[include octoeverywhere-system.cfg]

[update_manager mobileraker]
type: git_repo
path: /home/pi/mobileraker_companion
origin: https://github.com/Clon1998/mobileraker_companion.git
primary_branch:main
managed_services: mobileraker
env: /home/pi/mobileraker-env/bin/python
requirements: scripts/mobileraker-requirements.txt
install_script: scripts/install.sh

[file_manager]
enable_object_processing: True

[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main
[include moonraker-obico-update.cfg]

